// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef BASIC_IO_H
#define BASIC_IO_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <assert.h>

// Reg - basic_io_reg_block::LD
#define BASIC_IO_REG_BLOCK__LD__LD_bm 0xff
#define BASIC_IO_REG_BLOCK__LD__LD_bp 0
#define BASIC_IO_REG_BLOCK__LD__LD_bw 8
#define BASIC_IO_REG_BLOCK__LD__LD_reset 0x0

// Reg - basic_io_reg_block::SW
#define BASIC_IO_REG_BLOCK__SW__SW_bm 0xff
#define BASIC_IO_REG_BLOCK__SW__SW_bp 0
#define BASIC_IO_REG_BLOCK__SW__SW_bw 8
#define BASIC_IO_REG_BLOCK__SW__SW_reset 0x0

// Reg - basic_io_reg_block::BTN
#define BASIC_IO_REG_BLOCK__BTN__BTND_bm 0x1
#define BASIC_IO_REG_BLOCK__BTN__BTND_bp 0
#define BASIC_IO_REG_BLOCK__BTN__BTND_bw 1
#define BASIC_IO_REG_BLOCK__BTN__BTND_reset 0x0
#define BASIC_IO_REG_BLOCK__BTN__BTNR_bm 0x2
#define BASIC_IO_REG_BLOCK__BTN__BTNR_bp 1
#define BASIC_IO_REG_BLOCK__BTN__BTNR_bw 1
#define BASIC_IO_REG_BLOCK__BTN__BTNR_reset 0x0
#define BASIC_IO_REG_BLOCK__BTN__BTNC_bm 0x4
#define BASIC_IO_REG_BLOCK__BTN__BTNC_bp 2
#define BASIC_IO_REG_BLOCK__BTN__BTNC_bw 1
#define BASIC_IO_REG_BLOCK__BTN__BTNC_reset 0x0
#define BASIC_IO_REG_BLOCK__BTN__BTNL_bm 0x8
#define BASIC_IO_REG_BLOCK__BTN__BTNL_bp 3
#define BASIC_IO_REG_BLOCK__BTN__BTNL_bw 1
#define BASIC_IO_REG_BLOCK__BTN__BTNL_reset 0x0
#define BASIC_IO_REG_BLOCK__BTN__BTNU_bm 0x10
#define BASIC_IO_REG_BLOCK__BTN__BTNU_bp 4
#define BASIC_IO_REG_BLOCK__BTN__BTNU_bw 1
#define BASIC_IO_REG_BLOCK__BTN__BTNU_reset 0x0
#define BASIC_IO_REG_BLOCK__BTN__RSVD_bm 0xe0
#define BASIC_IO_REG_BLOCK__BTN__RSVD_bp 5
#define BASIC_IO_REG_BLOCK__BTN__RSVD_bw 3
#define BASIC_IO_REG_BLOCK__BTN__RSVD_reset 0x0

// Addrmap - basic_io_reg_block
typedef struct __attribute__ ((__packed__)) {
    uint8_t LD;
    uint8_t SW;
    uint8_t BTN;
} basic_io_reg_block_t;


static_assert(sizeof(basic_io_reg_block_t) == 0x3, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* BASIC_IO_H */
