// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef NEXYSVIDEOBASICIO_H
#define NEXYSVIDEOBASICIO_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <assert.h>

// Reg - basic_io_reg_block::BASIC_IO_REG
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__LD_bm 0xff
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__LD_bp 0
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__LD_bw 8
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__LD_reset 0x0
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__SW_bm 0xff00
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__SW_bp 8
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__SW_bw 8
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__SW_reset 0x0
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTND_bm 0x10000
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTND_bp 16
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTND_bw 1
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTND_reset 0x0
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNR_bm 0x20000
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNR_bp 17
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNR_bw 1
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNR_reset 0x0
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNC_bm 0x40000
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNC_bp 18
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNC_bw 1
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNC_reset 0x0
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNL_bm 0x80000
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNL_bp 19
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNL_bw 1
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNL_reset 0x0
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNU_bm 0x100000
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNU_bp 20
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNU_bw 1
#define BASIC_IO_REG_BLOCK__BASIC_IO_REG__BTNU_reset 0x0

// Addrmap - basic_io_reg_block
typedef struct __attribute__ ((__packed__)) {
    uint64_t BASIC_IO_REG;
} basic_io_reg_block_t;


static_assert(sizeof(basic_io_reg_block_t) == 0x8, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* NEXYSVIDEOBASICIO_H */
