
// This file was autogenerated by PeakRDL-uvm
package regmodel_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // Reg - basic_io_reg_block::BASIC_IO_REG
    class basic_io_reg_block__BASIC_IO_REG extends uvm_reg;
        rand uvm_reg_field LD;
        rand uvm_reg_field SW;
        rand uvm_reg_field BTND;
        rand uvm_reg_field BTNR;
        rand uvm_reg_field BTNC;
        rand uvm_reg_field BTNL;
        rand uvm_reg_field BTNU;

        function new(string name = "basic_io_reg_block__BASIC_IO_REG");
            super.new(name, 64, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.LD = new("LD");
            this.LD.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
            this.SW = new("SW");
            this.SW.configure(this, 8, 8, "RO", 1, 'h0, 1, 1, 0);
            this.BTND = new("BTND");
            this.BTND.configure(this, 1, 16, "RO", 1, 'h0, 1, 1, 0);
            this.BTNR = new("BTNR");
            this.BTNR.configure(this, 1, 17, "RO", 1, 'h0, 1, 1, 0);
            this.BTNC = new("BTNC");
            this.BTNC.configure(this, 1, 18, "RO", 1, 'h0, 1, 1, 0);
            this.BTNL = new("BTNL");
            this.BTNL.configure(this, 1, 19, "RO", 1, 'h0, 1, 1, 0);
            this.BTNU = new("BTNU");
            this.BTNU.configure(this, 1, 20, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : basic_io_reg_block__BASIC_IO_REG

    // Addrmap - basic_io_reg_block
    class basic_io_reg_block extends uvm_reg_block;
        rand basic_io_reg_block__BASIC_IO_REG BASIC_IO_REG;

        function new(string name = "basic_io_reg_block");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 8, UVM_NO_ENDIAN);
            this.BASIC_IO_REG = new("BASIC_IO_REG");
            this.BASIC_IO_REG.configure(this);

            this.BASIC_IO_REG.build();
            this.default_map.add_reg(this.BASIC_IO_REG, 'h0);
        endfunction : build
    endclass : basic_io_reg_block

endpackage: regmodel_pkg
